version: '3.1'

volumes:
  pg_project:

services:
  db:
    image: postgres:latest
    restart: always
    container_name: santa_bot_db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_project:/var/lib/postgresql/santa_bot
    ports:
      - "54345:5432"

  santa_bot:
    container_name: santa_bot
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - db